version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-16-may-2021/luna-group-project/scorpio/luna:latest
    env_file:
      - ./envs/prod.env
    command: "sh /scripts/run.sh"
    depends_on:
      - postgres
    volumes:
      - static-files:/static-files
      - media-files:/media-files
      #map static files from backend container to docker volume then send to frontend
      - frontend:/frontend/build


  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static-files:/static-files
      - media-files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend:/frontend


# declaration of files we use for volume mapping between containers
volumes:
  postgres_volume:
  static-files:
  media-files:
  frontend: