name: energy-lab
dependencies:
  - python=3.9.5
  - pip=21.1.2
  - psycopg2=2.8.5
  - pip:
      - Django==3.2.4
      - djangorestframework==3.12.4
      - djangorestframework_simplejwt==4.7.1
      - drf-yasg==1.20.0
      - pillow==8.2.0
      - gunicorn==20.1
      - flake8==3.9.2
      - django-cors-headers==3.7.0
