# Generated by Django 3.2.4 on 2021-07-14 13:55

from django.db import migrations, models
import route.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=route.models.route_directory_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=route.models.route_directory_path)),
                ('distance', models.FloatField()),
                ('average_grade', models.FloatField()),
                ('elevation', models.IntegerField()),
                ('steepest_km', models.FloatField()),
            ],
        ),
    ]
