# Generated by Django 3.2.4 on 2021-07-09 14:32

from django.db import migrations, models
import route.models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.route_directory_path),
        ),
        migrations.AddField(
            model_name='route',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.route_directory_path),
        ),
        migrations.AddField(
            model_name='route',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
