# Generated by Django 3.2.4 on 2021-07-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20210709_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='elevation',
            field=models.CharField(max_length=50),
        ),
    ]
