# Generated by Django 3.2.4 on 2021-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_alter_route_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='average_grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='elevation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='steepest_km',
            field=models.FloatField(),
        ),
    ]
