# Generated by Django 3.2.4 on 2021-07-09 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coach',
        ),
        migrations.AddField(
            model_name='user',
            name='coaches',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_user_coaches_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.From 9 up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
