# Generated by Django 3.2.4 on 2021-07-09 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210709_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coaches',
        ),
        migrations.AddField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='_user_user_clients_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
