# Generated by Django 3.2.4 on 2021-07-09 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210709_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
