# Generated by Django 3.2.4 on 2021-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='segment',
        ),
        migrations.AddField(
            model_name='segment',
            name='end',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
