# Generated by Django 3.2.4 on 2021-07-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0002_auto_20210707_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='elevation',
            field=models.FloatField(),
        ),
    ]
