<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-07-14 13:55
=======
# Generated by Django 3.2.4 on 2021-07-14 05:31
>>>>>>> d6b1218f26fd261935d72d03ed523ac19495c60c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('pat', models.IntegerField()),
                ('bike_weight', models.IntegerField(blank=True, default=7)),
                ('bike_type', models.FloatField(choices=[(0.95, 'Race Bike'), (0.92, 'Normal Bike')], default=0.95, max_length=10)),
                ('heart_rate', models.IntegerField(blank=True, default=175)),
                ('tire_pressure', models.FloatField(choices=[(0.0075, 3.5), (0.007, 4), (0.0065, 4.5), (0.0061, 5), (0.0058, 5.5), (0.0056, 6), (0.0054, 6.5), (0.0053, 7), (0.0051, 7.5), (0.0049, 8), (0.0047, 8.5), (0.0045, 9)], default=0.0053)),
                ('wind_condition', models.FloatField(choices=[(0, 0), (0.833333333, 3), (1.666666667, 6), (2.5, 9), (-0.833333333, -3), (-1.666666667, -6), (-2.5, -9)], default=0)),
                ('rider_position', models.FloatField(default=0.29833857)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
