<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-07-14 13:55
=======
# Generated by Django 3.2.4 on 2021-07-14 05:31
>>>>>>> d6b1218f26fd261935d72d03ed523ac19495c60c

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='route.Route'),
        ),
    ]
