# Generated by Django 3.2.4 on 2021-07-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_alter_session_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='bike_weight',
            field=models.IntegerField(blank=True, default=7),
        ),
    ]
