# Generated by Django 3.2.4 on 2021-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_alter_session_bike_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='heart_rate',
            field=models.IntegerField(blank=True, default=175),
        ),
    ]
